package cn.hashdata.bireme;


import org.apache.commons.lang3.StringUtils;

import java.util.regex.Pattern;

/**
 * @author: : yangyang.li
 * Created time: 2018/9/18.
 * Copyright(c) TTPai All Rights Reserved.
 * Description :
 */
public enum TableAlertTypeEnum {

    CREATE_DATABASE("^CREATE\\s+DATABASE\\s+.*",false),
    DROP_DATABASE("^DROP\\s+DATABASE\\s+.*",false),
    DROP_TABLE("^DROP\\s+TABLE\\s+.*",false),
    ALERT_TABLE_RENAME("^ALTER\\s+TABLE\\s+.*\\s+RENAME\\s.*",false),
    DROP_TABLE_COLUMN("^ALTER\\s+TABLE\\s+.*\\s+DROP\\s+COLUMN\\s+.*",false),
    ALTER_CHANGE_NAME("^ALTER\\s+TABLE\\s+.*\\s+CHANGE\\s+.*",false),


    ALTER_TABLE_ADD_COLUMN("^ALTER\\s+TABLE\\s+.*\\s+ADD\\s+(COLUMN)?\\s+.*",true),
    ALTER_TABLE_MODIFY_COLUMN("^ALTER\\s+TABLE\\s+.*\\s+MODIFY\\s+(COLUMN)?\\s+.*",true)
    ;
    //DROP TABLE `BOSS1_CITY_FF` /* generated by server */
    private String type;
    private Boolean operate;

    TableAlertTypeEnum(String type, Boolean operate){
        this.operate=operate;
        this.type=type;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Boolean getOperate() {
        return operate;
    }

    public void setOperate(Boolean operate) {
        this.operate = operate;
    }

    /**
     * 这6中DDL sql无须重写
     *@author: yangyang.li@ttpai.cn
     * @param sql
     *@return
     */
    public static boolean isPattern(String sql){
        if(StringUtils.isBlank(sql)){
            return false;
        }
        for(TableAlertTypeEnum typeEnum: TableAlertTypeEnum.values()){
            Boolean pattern= Pattern.matches(typeEnum.getType(),sql.toUpperCase().trim());
            if(pattern){
                return typeEnum.getOperate();
            }
        }
        return true;
    }

    /**
     * palo 不支持 属性名修改
     *@author: yangyang.li@ttpai.cn
     * @param sql
     *@return
     */
    public static boolean changeCoulmnName(String sql){
        Boolean pattern= Pattern.matches(ALTER_CHANGE_NAME.getType(),sql.toUpperCase().trim());
        return pattern;
    }



    public static void main(String[] args) {

        String sql="aLTER TABLE BOSS_ACCOUNT CHANGE COUNTRY  COUNTRY111 VARCHAR(100)";
        System.out.println(isPattern(sql));

    }
}
