package cn.hashdata.bireme;


import org.apache.commons.lang3.StringUtils;

import java.util.regex.Pattern;

/**
 * @author: : yangyang.li
 * Created time: 2018/9/18.
 * Copyright(c) TTPai All Rights Reserved.
 * Description :
 */
public enum TableAlertTypeEnum {

//    CREATE_DATABASE("^CREATE\\s+DATABASE\\s+.*",false),
//    DROP_DATABASE("^DROP\\s+DATABASE\\s+.*",false),
//    DROP_TABLE("^DROP\\s+TABLE\\s+.*",false),
    ALERT_TABLE_RENAME("^ALTER\\s+TABLE\\s+.*\\s+RENAME\\s.*",1),
    DROP_TABLE_COLUMN("^ALTER\\s+TABLE\\s+.*\\s+DROP\\s+COLUMN\\s+.*",2),
    ALTER_CHANGE_NAME("^ALTER\\s+TABLE\\s+.*\\s+CHANGE\\s+.*",3),


    ALTER_TABLE_ADD_COLUMN("^ALTER\\s+TABLE\\s+.*\\s+ADD\\s+(COLUMN)?\\s+.*",4),
    ALTER_TABLE_MODIFY_COLUMN("^ALTER\\s+TABLE\\s+.*\\s+MODIFY\\s+(COLUMN)?\\s+.*",5)
    ;
    //DROP TABLE `BOSS1_CITY_FF` /* generated by server */
    private String type;
    private Integer operate;

    TableAlertTypeEnum(String type, Integer operate){
        this.operate=operate;
        this.type=type;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getOperate() {
        return operate;
    }

    public void setOperate(Integer operate) {
        this.operate = operate;
    }

    /**
     * 这6中DDL sql无须重写
     *@author: yangyang.li@ttpai.cn
     * @param sql
     *@return
     */
    public static Integer isPattern(String sql){
        if(StringUtils.isBlank(sql)){
            return 0;
        }
        for(TableAlertTypeEnum typeEnum: TableAlertTypeEnum.values()){
            Boolean pattern= Pattern.matches(typeEnum.getType(),sql.toUpperCase().trim());
            if(pattern){
                return typeEnum.getOperate();
            }
        }
        return 0;
    }


    public static void main(String[] args) {

        String sql="aLTER TABLE BOSS_ACCOUNT CHANGE COUNTRY  COUNTRY111 VARCHAR(100)";
        System.out.println(isPattern(sql));

    }
}
