package cn.hashdata.bireme;

import com.alibaba.fastjson.JSONObject;

import java.util.Comparator;
import java.util.Map;
import java.util.TreeMap;

/**
 * @author: : yangyang.li
 * Created time: 2018/11/28.
 * Copyright(c) TTPai All Rights Reserved.
 * Description :
 */
public class Test {


    public static void main(String[] args) {

            String sql="DROP TABLE `boss_violate_bak` /* generated by server */";

                System.out.println(sql.replaceAll("/\\*.*\\*/","").replaceAll("`",""));



    }
}
